export interface Brew {
  id: number;
  name: string;
  style: string;
  abv: number;
  ibu?: number; // IBU can have decimal values
  description?: string;
  brewDate?: string;
  kegLevel?: number;
  brewUuid?: string;
  apiBrewUuid?: string;
  recipeId?: string; // Reference to the recipe
  // Snake case versions from the database
  brew_date?: string;
  keg_level?: number;
  brew_uuid?: string;
  api_brew_uuid?: string;
  recipe_id?: string;
  created_at?: string;
  updated_at?: string;
}

// For backward compatibility
export type Beer = Brew;

export interface BrewCreateInput {
  name: string;
  style: string;
  abv: number;
  ibu?: number; // IBU can have decimal values
  description?: string;
  brewDate?: string;
  kegLevel?: number;
  brewUuid?: string; // UUID provided by the companion app
  apiBrewUuid?: string; // UUID generated by the API (normally not provided in create requests)
  recipeId?: string; // Reference to the recipe
}

// For backward compatibility
export type BeerCreateInput = BrewCreateInput;
