import Link from 'next/link';
import { quickReviewExample, standardReviewExample, expertReviewExample, reviewResponseExample } from './review-examples';

export default function ApiDocsPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 font-patua">TAPPr API Documentation</h1>

      <div className="mb-8">
        <p className="text-gray-600 mb-4 font-montserrat">
          Welcome to the TAPPr API documentation. This API allows you to interact with beer data for your homebrewing needs.
        </p>

        <div className="bg-amber-50 border-l-4 border-amber-500 p-4 mb-4">
          <h3 className="text-lg font-bold mb-2 font-patua">UUID System</h3>
          <p className="text-gray-700 mb-2 font-montserrat">
            The TAPPr API uses two UUID fields for brews (beers):
          </p>
          <ul className="list-disc pl-5 mb-2 font-montserrat">
            <li><strong>api_brew_uuid</strong>: A UUID generated by the API that serves as the unique immutable key for the record in the database.</li>
            <li><strong>brewUuid</strong>: A UUID provided by the companion app that serves as a reference for the app.</li>
          </ul>
          <p className="text-gray-700 font-montserrat">
            When creating a new brew, you can provide a <code className="bg-gray-100 px-1">brewUuid</code> from the companion app. The API will generate a new <code className="bg-gray-100 px-1">api_brew_uuid</code> for the brew and return both UUIDs in the response. Reviews reference brews using the <code className="bg-gray-100 px-1">api_brew_uuid</code> field.
          </p>
        </div>
      </div>

      <div className="space-y-8">
        <section className="border-b pb-6">
          <h2 className="text-2xl font-bold mb-4 font-patua">Endpoints</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get All Brews</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/beers</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns a list of all brews (beers).</p>
              <div className="bg-gray-100 p-3 rounded">
                <pre className="text-sm overflow-auto">
                  {JSON.stringify([
                    {
                      id: 1,
                      name: 'Hoppy IPA',
                      style: 'India Pale Ale',
                      abv: 6.5,
                      // other fields...
                    }
                  ], null, 2)}
                </pre>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get Brew by ID</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/beers/{'{id}'}</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns a specific brew (beer) by ID.</p>
              <div className="bg-gray-100 p-3 rounded">
                <pre className="text-sm overflow-auto">
                  {JSON.stringify(
                    {
                      id: 1,
                      name: 'Hoppy IPA',
                      style: 'India Pale Ale',
                      abv: 6.5,
                      ibu: 65.5,
                      description: 'A hoppy IPA with citrus and pine notes',
                      brewDate: '2023-10-15',
                      kegLevel: 85,
                      brewUuid: '550e8400-e29b-41d4-a716-446655440000',
                      api_brew_uuid: '7dfb14c4-d288-4b1e-ae69-ec2d733aa434',
                    },
                    null,
                    2
                  )}
                </pre>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get Brew by API UUID</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/beers/api/{'{apiBrewUuid}'}</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns a specific brew (beer) by its API-generated UUID.</p>
              <div className="bg-gray-100 p-3 rounded">
                <pre className="text-sm overflow-auto">
                  {JSON.stringify(
                    {
                      id: 1,
                      name: 'Hoppy IPA',
                      style: 'India Pale Ale',
                      abv: 6.5,
                      ibu: 65.5,
                      description: 'A hoppy IPA with citrus and pine notes',
                      brewDate: '2023-10-15',
                      kegLevel: 85,
                      brewUuid: '550e8400-e29b-41d4-a716-446655440000',
                      api_brew_uuid: '7dfb14c4-d288-4b1e-ae69-ec2d733aa434',
                    },
                    null,
                    2
                  )}
                </pre>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Add New Brew</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>POST /api/beers/add</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Adds a new brew (beer) to the system.</p>
              <div className="mb-2">
                <h4 className="font-semibold font-patua">Request Body:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        name: 'New Brew',
                        style: 'IPA',
                        abv: 5.5,
                        ibu: 40.5,
                        description: 'Description of the brew',
                        brewDate: '2024-04-01', // Optional
                        kegLevel: 100, // Optional
                        brewUuid: '550e8400-e29b-41d4-a716-446655440001' // Optional, UUID from companion app
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
              <div>
                <h4 className="font-semibold font-patua">Response:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        message: 'Brew added successfully',
                        brew: {
                          id: 4,
                          name: 'New Brew',
                          style: 'IPA',
                          abv: 5.5,
                          ibu: 40.5,
                          description: 'Description of the brew',
                          brewDate: '2024-04-01',
                          kegLevel: 100,
                          brewUuid: '550e8400-e29b-41d4-a716-446655440001',
                          api_brew_uuid: '7dfb14c4-d288-4b1e-ae69-ec2d733aa434',
                          createdAt: '2024-04-15T14:30:00Z',
                          updatedAt: '2024-04-15T14:30:00Z'
                        },
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Update Brew</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>PATCH /api/beers/{'{id}'}/update</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Updates an existing brew (beer).</p>
              <div className="mb-2">
                <h4 className="font-semibold font-patua">Request Body:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        name: 'Updated Beer Name', // Only include fields you want to update
                        kegLevel: 75,
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
              <div>
                <h4 className="font-semibold font-patua">Response:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        message: 'Brew updated successfully',
                        brew: {
                          id: 1,
                          name: 'Updated Brew Name',
                          style: 'India Pale Ale',
                          abv: 6.5,
                          ibu: 65.5,
                          description: 'A hoppy IPA with citrus and pine notes',
                          brewDate: '2023-10-15',
                          kegLevel: 75,
                          brewUuid: '550e8400-e29b-41d4-a716-446655440000',
                          api_brew_uuid: '7dfb14c4-d288-4b1e-ae69-ec2d733aa434',
                          createdAt: '2023-11-15T14:30:00Z',
                          updatedAt: '2024-04-15T14:30:00Z'
                        },
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Delete Brew</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>DELETE /api/beers/{'{id}'}/delete</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Deletes a brew (beer) from the system.</p>
              <div>
                <h4 className="font-semibold font-patua">Response:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        message: 'Brew deleted successfully',
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="border-b pb-6 mt-8">
          <h2 className="text-2xl font-bold mb-4 font-patua">Review Endpoints</h2>

          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get All Reviews</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/reviews</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns a list of all reviews.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get Review by ID</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/reviews/{'{id}'}</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns a specific review by ID.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get Reviews by API Brew UUID</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/reviews/api-brew/{'{apiBrewUuid}'}</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns all reviews for a specific brew using the API-generated UUID (primary reference).</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Get Reviews by Companion App Brew UUID</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>GET /api/reviews/brew/{'{brewUuid}'}</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Returns all reviews for a specific brew using the companion app UUID (for backward compatibility).</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Add Quick Review</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>POST /api/reviews/add</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Adds a new quick review.</p>
              <div className="mb-2">
                <h4 className="font-semibold font-patua">Request Body:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(quickReviewExample, null, 2)}
                  </pre>
                </div>
              </div>
              <div>
                <h4 className="font-semibold font-patua">Response:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(reviewResponseExample, null, 2)}
                  </pre>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Add Standard Review</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>POST /api/reviews/add</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Adds a new standard review with more detailed ratings.</p>
              <div className="mb-2">
                <h4 className="font-semibold font-patua">Request Body:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(standardReviewExample, null, 2)}
                  </pre>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Add Expert Review</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>POST /api/reviews/add</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Adds a new expert review with comprehensive ratings.</p>
              <div className="mb-2">
                <h4 className="font-semibold font-patua">Request Body:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(expertReviewExample, null, 2)}
                  </pre>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Update Review</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>PATCH /api/reviews/{'{id}'}/update</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Updates an existing review.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-2 font-patua">Delete Review</h3>
              <div className="bg-gray-100 p-3 rounded mb-2">
                <code>DELETE /api/reviews/{'{id}'}/delete</code>
              </div>
              <p className="text-gray-600 mb-2 font-montserrat">Deletes a review from the system.</p>
              <div>
                <h4 className="font-semibold font-patua">Response:</h4>
                <div className="bg-gray-100 p-3 rounded">
                  <pre className="text-sm overflow-auto">
                    {JSON.stringify(
                      {
                        message: 'Review deleted successfully',
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 font-patua">Authentication</h2>
          <p className="text-gray-600 mb-2 font-montserrat">
            The API is protected with an API key. You must include the API key in the header of each request.
          </p>

          <div className="mt-4">
            <h3 className="text-xl font-semibold mb-2 font-patua">API Key Authentication</h3>
            <p className="text-gray-600 mb-2 font-montserrat">
              Include the API key in the <code className="bg-gray-100 px-2 py-1 rounded">X_API_Key</code> header of your requests.
              <span className="text-red-500 font-bold">Note:</span> Use underscore (_) instead of dash (-) in the header name.
            </p>

            <div className="bg-gray-100 p-3 rounded mb-4">
              <pre className="text-sm overflow-auto">
                {`// Example using fetch
fetch('https://tappr.beer/api/beers', {
  headers: {
    'X_API_Key': 'your-api-key-here'
  }
})`}
              </pre>
            </div>

            <div className="bg-gray-100 p-3 rounded mb-4">
              <pre className="text-sm overflow-auto">
                {`// Example using axios
axios.get('https://tappr.beer/api/beers', {
  headers: {
    'X_API_Key': 'your-api-key-here'
  }
})`}
              </pre>
            </div>

            <div className="bg-gray-100 p-3 rounded">
              <pre className="text-sm overflow-auto">
                {`// Example using curl
curl -X GET \
  -H "X_API_Key: your-api-key-here" \
  https://tappr.beer/api/beers`}
              </pre>
            </div>
          </div>
        </section>
      </div>

      <div className="mt-8">
        <Link href="/" className="text-amber-600 hover:text-amber-800 font-montserrat">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
